package:
  name: rft1d
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
   path: ../


build:
  script: python setup.py install
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

    
requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python
    - scipy >=0.15
    - numpy >=1.9
    - future


test:
  imports:
    - rft1d



about:
  home: http://www.spm1d.org/rft1d/
  license: GPL
