name: push-test-pypi

on:
  push:
    branches: [ v0.2 ]


jobs:
  publish-test-pypi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install build dependencies
      run: python -m pip install -U setuptools wheel build pytest pytest-explicit
    - name: Build
      run: python -m build .
    - name: Test with pytest
      run: |
        cd tests
        pytest
    # - name: Publish
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     password: ${{ secrets.TEST_PYPI_TOKEN }}
    #     skip_existing: true
    #     repository_url: https://test.pypi.org/legacy/

